### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by NightRaidGamer** [Hakkuraifu/PS4Linux-Documentation#1]
hello I would like to know the difference between the three "Initramfs.cpio.gz." Psxita, Hippie68 and Nazky

and I would also like to know if I follow your How to make my own OS tutorial, will it work on these 5 distributions: kali linux, fedora 35, Garuda Linux, Pop!_OS and elementary OS. It is compatible?

**Comment by Nazky** [comment]
hi for the difference the three "Initramfs.cpio.gz."

Psxita is the orignal one not really recommended anymore

Hippie68 is the one with the usb fix (go [here](https://github.com/hippie68/psxitarch-how-to#1-get-the-required-files) to see what the "usb fix" is)

Nazky is the one with the fix of hippie and a script to install the os in the hdd

for the os garuda is a arch based is maybe going to work, for fedora i don't have the drivers but you can find precompiled drivers on the github of itmania it's maybe going to work, for the others it's debian based and we don't have the drivers for it yet (maybe we can make something with makedeb i don't have try yet) i know itmania have them precompiled but for what i have try it's not working

**Comment by NightRaidGamer** [comment]
> hi for the difference the three "Initramfs.cpio.gz."
> 
> Psxita is the orignal one not really recommended anymore
> 
> Hippie68 is the one with the usb fix (go [here](https://github.com/hippie68/psxitarch-how-to#1-get-the-required-files) to see what the "usb fix" is)
> 
> Nazky is the one with the fix of hippie and a script to install the os in the hdd
> 
> for the os garuda is a arch based is maybe going to work, for fedora i don't have the drivers but you can find precompiled drivers on the github of itmania it's maybe going to work, for the others it's debian based and we don't have the drivers for it yet (maybe we can make something with makedeb i don't have try yet) i know itmania have them precompiled but for what i have try it's not working

thanks i will try garuda linux
