### ISSUE TITLE
Question about OS size

### ISSUE THREAD

**Issue by gabriel-maxx** [Hakkuraifu/PS4Linux-Documentation#3]
hello I would like to know why the limit is 3.2GB? Is there any way to increase it to 4GB?

**Comment by vbajs** [comment]
> hello I would like to know why the limit is 3.2GB? Is there any way to increase it to 4GB?

That's because of the usage of FAT32 filesystem, which only supports a maximum of 3.2GB files (it's in the name)

**Comment by gabriel-maxx** [comment]
> > hello I would like to know why the limit is 3.2GB? Is there any way to increase it to 4GB?
> 
> That's because of the usage of FAT32 filesystem, which only supports a maximum of 3.2GB files (it's in the name)

I researched and it says that the fat32 limit is 4gb and I've also put several 4gb files using fat 32 and it works... but if it's a little more than 4gb then no.

**Comment by nickcat1** [comment]
You can use exfat instead of fat32. exfat will still work with Linux.
